# Python Django
# Test a Django project on multiple versions of Python.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python35:
      PYTHON_VERSION: '3.5'
    Python36:
      PYTHON_VERSION: '3.6'
    Python37:
      PYTHON_VERSION: '3.7'
  maxParallel: 3

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(PYTHON_VERSION)'
    architecture: 'x64'

- task: PythonScript@0
  displayName: 'Export project path'
  inputs:
    scriptSource: 'inline'
    script: |
      """Search all subdirectories for `manage.py`."""
      from glob import iglob
      from os import path
      # Python >= 3.5
      manage_py = next(iglob(path.join('**', 'manage.py'), recursive=True), None)
      if not manage_py:
          raise SystemExit('Could not find a Django project')
      project_location = path.dirname(path.abspath(manage_py))
      print('Found Django project in', project_location)
      print('##vso[task.setvariable variable=projectRoot]{}'.format(project_location))

- script: |
    # python -m pip install --upgrade pip setuptools wheel
    # pip install -r requirements.txt
    # pip install unittest-xml-reporting
    pip install -U selenium
    pip install django
    python manage.py makemigrations
    python manage.py migrate

    
    sudo apt-get install libxssl libappindicator1 libindicator7
    wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

    sudo dpkg -i google-chrome*.deb
    sudo apt-get install -f
    
    # wget -N https://chromedriver.storage.googleapis.com/2.26/chromedriver_linux64.zip
    wget -N https://chromedriver.storage.googleapis.com/78.0.3904.70/chromedriver_linux64.zip
    unzip chromedriver_linux64.zip
    chmod 755 chromedriver

    sudo mv -f chromedriver /usr/local/chromedriver
    sudo ln -s /usr/local/chromedriver /usr/local/bin/chromedriver
    sudo ln -s /usr/local/chromedriver /usr/bin/chromedriver

    google-chrome --version

  displayName: 'Install prerequisites'

- script: |
    pushd '$(projectRoot)'
    python manage.py test selenium_test
  displayName: 'Run tests'
